services:
  playground-be:
    platform: linux/amd64
    container_name: ${ENV:-dev}-playground-be
    build: .
    image: boschvn/playground-be:${IMAGE_TAG:-latest}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - playground-db
      - upload
    networks:
      - node-network
    restart: ${RESTART_POLICY:-always}

  playground-db:
    container_name: ${ENV:-dev}-playground-db
    image: mongo:4.4.6-bionic
    ports:
      - '${MONGO_EXPOSE_PORT}:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
    restart: ${RESTART_POLICY:-always}

  upload:
    platform: linux/amd64
    container_name: ${ENV:-dev}-upload
    build: ./upload/
    image: boschvn/upload:${IMAGE_TAG:-latest}
    ports:
      - '${UPLOAD_PORT}:${UPLOAD_PORT}'
    volumes:
      - '${UPLOAD_PATH}:/usr/src/upload/data'

    networks:
      - node-network
    restart: ${RESTART_POLICY:-always}

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
