services:
  kong:
    platform: linux/amd64
    image: kong:3.7.1-ubuntu
    container_name: ${ENV:-dev}-kong
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
    ports:
      - "${KONG_PROXY_PORT}:8443"

    restart: ${RESTART_POLICY:-always}
    networks:
      - node-network
    volumes:
      - "./:/kong/declarative/"
    depends_on:
      - playground-be

  playground-be:
    platform: linux/amd64
    container_name: ${ENV:-dev}-playground-be
    build: .
    image: boschvn/playground-be:${IMAGE_TAG:-latest}
    depends_on:
      - playground-db
      - upload
    networks:
      - node-network
    restart: ${RESTART_POLICY:-always}

  playground-db:
    container_name: ${ENV:-dev}-playground-db
    image: mongo:4.4.6-bionic
    ports:
      - '${MONGO_EXPOSE_PORT}:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
    restart: ${RESTART_POLICY:-always}

  upload:
    platform: linux/amd64
    container_name: ${ENV:-dev}-upload
    build: ./upload/
    image: boschvn/upload:${IMAGE_TAG:-latest}
    volumes:
      - '${UPLOAD_PATH}:/usr/src/upload/data'
    networks:
      - node-network
    restart: ${RESTART_POLICY:-always}

volumes:
  dbdata:


networks:
  node-network:
    driver: bridge
