services:

  kong:
    platform: linux/amd64
    image: kong:3.7.1-ubuntu
    container_name: ${ENV:-dev}-kong
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_NGINX_WORKER_PROCESSES: ${KONG_NGINX_WORKER_PROCESSES:-auto}
    ports:
      - "${KONG_PROXY_PORT}:8000"

    restart: always
    networks:
      - node-network
    volumes:
      - "./:/kong/declarative/"
    depends_on:
      - playground-be

  playground-be:
    platform: linux/amd64
    container_name: ${ENV:-dev}-playground-be
    build: .
    image: boschvn/playground-be:${IMAGE_TAG:-latest}
    env_file:
      - .env
    depends_on:
      - playground-db
      - upload
    networks:
      - node-network
    restart: always
    command: yarn start

  playground-db:
    container_name: ${DB_CONTAINER_NAME:-playground-db}
    image: mongo:4.4.6-bionic
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
    restart: always

  upload:
    platform: linux/amd64
    container_name: ${ENV:-dev}-upload
    image: boschvn/upload:1.0.0
    env_file:
      - .env
    volumes:
      - '${UPLOAD_PATH}:/usr/src/upload/data'
    networks:
      - node-network
    restart: always
    command: npm run prod

volumes:
  dbdata:


networks:
  node-network:
    driver: bridge
