version: '3'

services:
  playground-be:
    build: .
    image: playground-be
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - playground-db
    volumes:
      - .:/usr/src/playground-be
    networks:
      - node-network

  playground-db:
    image: mongo:4.4.6-bionic
    ports:
      - '${MONGO_EXPOSE_PORT}:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:


networks:
  node-network:
    driver: bridge
