version: '3'

services:
  playground-be:
    build: .
    image: playground-be
    environment:
      - PORT=9800
      - MONGODB_URL=mongodb://playground-db:27017/playground-be
    ports:
      - '9800:9800'
    depends_on:
      - playground-db
    volumes:
      - .:/usr/src/playground-be
    networks:
      - node-network

  playground-db:
    image: mongo:4.2.1-bionic
    ports:
      - '27018:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:


networks:
  node-network:
    driver: bridge
