services:
  playground-be:
    command: yarn dev -L
    volumes:
      - .:/usr/src/playground-be
    restart: no

  upload:
    command: npm start
    restart: no

  playground-db:
    ports:
      - "27017:27017"
    restart: no

  kong:
    restart: no
