# upload/Dockerfile
version: '3'

services:
  playground-be:
    build: .
    image: playground-be
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - playground-db
      - upload
    volumes:
      - .:/usr/src/playground-be
    networks:
      - node-network

  playground-db:
    image: mongo:4.4.6-bionic
    ports:
      - '${MONGO_EXPOSE_PORT}:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  upload:
    build: ./upload/
    image: upload
    ports:
      - '${UPLOAD_PORT}:${UPLOAD_PORT}'
    volumes:
      - ./upload:/usr/src/upload
      - /usr/src/upload/node_modules/
      - '${UPLOAD_PATH}:/usr/src/upload/data'
    networks:
      - node-network


volumes:
  dbdata:


networks:
  node-network:
    driver: bridge
